### ISSUE TITLE
Add email designs to my projects

### ISSUE THREAD

**Issue by troyvassalotti** [troyvassalotti/personal-site#2]
This page would house any and all email designs I create and want to show off.

Could be ones I design from templates or ones I created through TK if they exist.

**Comment by actionhamilton** [comment]
Take the email code from my HubSpot email template in my work files (the most updated custom email that isn't in HubL) and use that to reference Email 1.

**Comment by actionhamilton** [comment]
With the email, continue designing to add a line for "view this email in your browser."
